# Generated by Django 4.2.21 on 2025-07-07 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0005_delete_accountsubscriptionfaq'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mongo_id', models.CharField(max_length=100)),
                ('amenity_type', models.CharField(max_length=20)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_clicks', to='registration.user')),
            ],
            options={
                'ordering': ['-clicked_at'],
                'unique_together': {('user', 'mongo_id')},
            },
        ),
        migrations.CreateModel(
            name='SavedLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mongo_id', models.CharField(max_length=100)),
                ('amenity_type', models.CharField(max_length=20)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_locations', to='registration.user')),
            ],
            options={
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'mongo_id')},
            },
        ),
    ]
