# Generated by Django 4.2.21 on 2025-07-09 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsActionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('referral', 'Referral'), ('map', 'Map'), ('post', 'Post'), ('share', 'Share'), ('coupon', 'Coupon'), ('donation', 'Donation'), ('orders', 'Orders'), ('subscription', 'Subscription'), ('purchase', 'Purchase')], max_length=32, unique=True)),
                ('default_points', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PointsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='points.pointsactiontype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.user')),
            ],
        ),
    ]
