# Generated by Django 4.2.21 on 2025-07-09 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ngopost', '0001_initial'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order_id', models.CharField(blank=True, help_text='Unique order ID for the donation (alphanumeric)', max_length=64, null=True, unique=True)),
                ('payment_date', models.DateTimeField(blank=True, help_text='Date and time when payment was made', null=True)),
                ('gst', models.DecimalField(blank=True, decimal_places=2, help_text='GST amount charged on platform fee', max_digits=12, null=True)),
                ('platform_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Platform fee charged for the donation', max_digits=12, null=True)),
                ('amount_to_ngo', models.DecimalField(blank=True, decimal_places=2, help_text='Amount transferred to NGO after fees', max_digits=12, null=True)),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction ID (alphanumeric)', max_length=64, null=True, unique=True)),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI'), ('Card', 'Card'), ('NetBanking', 'Net Banking'), ('Wallet', 'Wallet'), ('Other', 'Other')], default='UPI', max_length=32)),
                ('pan_number', models.CharField(blank=True, max_length=32, null=True)),
                ('pan_document', models.FileField(blank=True, null=True, upload_to='common_docs/donation_docs/')),
                ('payment_status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed')], default='Success', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ngopost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='ngopost.ngopost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='registration.user')),
            ],
        ),
    ]
