# Generated by Django 5.2.2 on 2025-06-30 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="issueoption",
            unique_together={("issue_type", "name")},
        ),
    ]
