# Generated by Django 5.2.2 on 2025-07-01 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0003_faq"),
    ]

    operations = []
