# Generated by Django 4.2.23 on 2025-07-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_alter_faq_user_alter_supportticket_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatOptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('advertiser', 'Advertiser'), ('client', 'Client'), ('ngo', 'NGO'), ('provider', 'Medical Provider'), ('user', 'User')], help_text="The type of user this chatbot content is for (e.g., 'ngo', 'provider', 'user').", max_length=32, unique=True)),
                ('options_data', models.JSONField(default=dict, help_text='JSON structure containing initial message and chat options.')),
                ('is_active', models.BooleanField(default=True, help_text='Is this chat option group currently active and available?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chat Option Group',
                'verbose_name_plural': 'Chat Option Groups',
                'ordering': ['user_type'],
            },
        ),
    ]
