# Generated by Django 5.2.2 on 2025-06-26 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0002_accountsubscriptionfaq"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="accountsubscriptionfaq",
            table="account_subscription_faq",
        ),
    ]
