# Generated by Django 4.2.21 on 2025-06-30 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_accountsubscriptionfaq_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='inapp_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='promotions_and_offers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='push_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='quite_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='quite_mode_end_time',
            field=models.TimeField(blank=True, default=datetime.time(6, 0), null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='quite_mode_start_time',
            field=models.TimeField(blank=True, default=datetime.time(22, 0), null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='regulatory_alerts',
            field=models.BooleanField(default=True),
        ),
    ]
