# Generated by Django 5.2.2 on 2025-07-02 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "registration",
            "0004_user_email_notifications_user_inapp_notifications_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="AccountSubscriptionFAQ",
        ),
    ]
