# Generated by Django 5.2.4 on 2025-07-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0005_delete_accountsubscriptionfaq"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="AdvertiserType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
    ]
