# Generated by Django 5.2.4 on 2025-07-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0006_adservice_advertisertype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisertype",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
