# Generated by Django 5.2.4 on 2025-07-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0007_alter_advertisertype_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name="AdvertiserType",
        ),
        migrations.AlterField(
            model_name="adservice",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
