# Generated by Django 5.2.4 on 2025-07-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0008_clienttype_delete_advertisertype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adservice",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="clienttype",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
