# Generated by Django 4.2.23 on 2025-06-27 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NGOPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=80)),
                ('description', models.TextField(max_length=500)),
                ('tags', models.CharField(help_text='Comma-separated tags', max_length=255)),
                ('post_type', models.CharField(choices=[('Education', 'Education'), ('Health', 'Health'), ('Food', 'Food')], max_length=20)),
                ('donation_frequency', models.CharField(choices=[('One-time', 'One-time'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='One-time', max_length=20)),
                ('target_donation', models.DecimalField(decimal_places=2, max_digits=12)),
                ('donation_received', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('age_group', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('spending_power', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Closed', 'Closed'), ('Paused', 'Paused')], default='Ongoing', max_length=10)),
                ('creative1', models.FileField(upload_to='post_creatives/')),
                ('creative2', models.FileField(blank=True, null=True, upload_to='post_creatives/')),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ngo_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
