# Generated by Django 4.2.23 on 2025-06-27 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngopost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngopost',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ngo_posts', to='registration.user'),
        ),
    ]
