# Generated by Django 4.2.23 on 2025-06-30 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_accountsubscriptionfaq_table'),
        ('ngopost', '0002_alter_ngopost_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngopost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ngo_posts', to='registration.user'),
        ),
    ]
