# Generated by Django 4.2.23 on 2025-07-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngopost', '0003_alter_ngopost_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngopost',
            name='last_downloaded',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ngopost',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
