# Generated by Django 4.2.23 on 2025-07-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngopost', '0004_ngopost_last_downloaded_ngopost_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngopost',
            name='creative1',
            field=models.FileField(upload_to='document/ngo_docs/post_creatives/'),
        ),
        migrations.AlterField(
            model_name='ngopost',
            name='creative2',
            field=models.FileField(blank=True, null=True, upload_to='document/ngo_docs/post_creatives/'),
        ),
    ]
