# Generated by Django 4.2.23 on 2025-07-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngopost', '0005_alter_ngopost_creative1_alter_ngopost_creative2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngopost',
            name='creative1',
            field=models.FileField(upload_to='ngo_docs/post_creatives/'),
        ),
        migrations.AlterField(
            model_name='ngopost',
            name='creative2',
            field=models.FileField(blank=True, null=True, upload_to='ngo_docs/post_creatives/'),
        ),
    ]
