# Generated by Django 4.2.23 on 2025-07-08 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngopost', '0002_add_dropdown_defaults'),
        ('ngopost', '0007_ageoption_countryoption_donationfrequencyoption_and_more'),
    ]

    operations = [
    ]
